/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as databaseSol from "./Database.sol";
export type { databaseSol };
import type * as v1Sol from "./v1.sol";
export type { v1Sol };
export * as factories from "./factories";
export type { DAOEnrollment } from "./Database.sol/DAOEnrollment";
export { DAOEnrollment__factory } from "./factories/Database.sol/DAOEnrollment__factory";
export type { MembersDATA } from "./v1.sol/MembersDATA";
export { MembersDATA__factory } from "./factories/v1.sol/MembersDATA__factory";
